### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = []
for a in range(10):
  arr.append(np.random.randint(50))

print(f"Valores aleatorios: {arr}")

media = np.mean(arr)
desvioP = np.std(arr)

print(f"Media: {media}")
print(f"Desvio padrão: {desvioP}")

#Solução do prof
arr.append(np.random.randint(50), size=10)

Valores aleatorios: [34, 0, 28, 47, 39, 39, 26, 0, 38, 24]
Media: 27.5
Desvio padrão: 15.246311029229332


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)
  
print(f"Valores aleatorios: \n {arr} \n ")

for i in arr:
  if i <= 0.5:
    print(np.sqrt(i))

#Solução do prof
arr = np.random.rand(10)
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

Valores aleatorios: 
 [0.08383545 0.06267644 0.93992335 0.42353474 0.4282025  0.97221607
 0.85378594 0.18402306 0.81758373 0.42077541] 
 
0.2895435265557498
0.2503526401734667
0.6507954691329906
0.6543718394280725
0.4289790927596099
0.6486720350848489


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)
print(f"Matriz: \n {matriz} \n")

print("Maiores valores de cada linha")
print(np.max(matriz, axis=1))

Matriz: 
 [[[0.22029161 0.15293246 0.26880409]
  [0.16696435 0.36077838 0.40428582]
  [0.75617456 0.06841999 0.56303626]]

 [[0.74999695 0.97703153 0.20552539]
  [0.91426008 0.75564112 0.94106767]
  [0.65389423 0.59306606 0.18281572]]

 [[0.38774063 0.13283546 0.13649643]
  [0.07863901 0.00160385 0.19349164]
  [0.01401182 0.393021   0.8365254 ]]] 

Maiores valores de cada linha
[[0.75617456 0.36077838 0.56303626]
 [0.91426008 0.97703153 0.94106767]
 [0.38774063 0.393021   0.8365254 ]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)
print(f"Valores aleatorios:\n {matriz}\n")

media = np.mean(matriz, axis=1) #axis=1 indica que queremos a media de cada linha da matriz
print(f"Media: {media}\n")

matrizMenosMedia = matriz - media[:, np.newaxis] #Primeiro transpomos o array que guarda as medias, depois subtraimos da matriz
print(f"Matriz Menos Media: \n {matrizMenosMedia}\n")

Valores aleatorios:
 [[8.87293905e-01 3.51944932e-01 1.82352711e-01 2.92027467e-01
  1.22152311e-01]
 [4.14177387e-01 2.17694467e-01 8.01872885e-01 5.95041109e-01
  6.82437166e-01]
 [2.79666517e-01 7.98231069e-01 2.45206850e-01 6.59504914e-01
  6.10656904e-01]
 [4.43408070e-01 6.79295723e-01 8.52848535e-01 8.98991979e-01
  3.73051673e-02]
 [8.18230890e-05 1.07705807e-01 3.15959610e-01 5.36286602e-01
  7.55305065e-01]]

Media: [0.36715427 0.5422446  0.51865325 0.58236989 0.34306778]

Matriz Menos Media: 
 [[ 0.52013964 -0.01520933 -0.18480155 -0.0751268  -0.24500195]
 [-0.12806722 -0.32455014  0.25962828  0.05279651  0.14019256]
 [-0.23898673  0.27957782 -0.2734464   0.14085166  0.09200365]
 [-0.13896182  0.09692583  0.27047864  0.31662208 -0.54506473]
 [-0.34298596 -0.23536197 -0.02710817  0.19321882  0.41223728]]



### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4) 

principal = np.diag(matriz) #Diag pega a diagonal da Matriz
secundaria = np.diag(np.fliplr(matriz)) #fliplr espelha a posição dos elementos mantendo os valores das linhas 
mediaDiagonais = np.mean([principal, secundaria]) # calcular a media com os valores das duas diagonais
desvioP = np.std([principal, secundaria]) # calcular o desvio padrão com os valores das duas diagonais
                     
print(f"Matriz:\n {matriz} \n")
print(f"Diagonal principal: {principal}")
print(f"Diagonal secundaria: {secundaria}")
print(f"Media Diagonais: {mediaDiagonais}")
print(f"desvio Padrao: {desvioP}")

Matriz:
 [[0.10949031 0.9940922  0.43209546 0.92661517]
 [0.59384706 0.14646173 0.40911796 0.60046358]
 [0.77886346 0.97687286 0.89742005 0.59967082]
 [0.82940716 0.98981658 0.43615624 0.34985628]] 

Diagonal principal: [0.10949031 0.14646173 0.89742005 0.34985628]
Diagonal secundaria: [0.92661517 0.40911796 0.97687286 0.82940716]
Media Diagonais: 0.5806551906163628
desvio Padrao: 0.3413406893496283
